INSERT INTO prep_tasks (id, session_id, item_type, item_id, item_name, quantity_required, quantity_actual, for_orders_json, assigned_to, assigned_name, expected_minutes, started_at, finished_at, actual_minutes, status, notes, sort_order) VALUES
  (1, 1, 'flex_product', 13430, 'Em Seinemeier', 1, NULL, '["Em Seinemeier ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 0),
  (2, 2, 'flex_product', 13430, 'Em Seinemeier', 1, NULL, '["Em Seinemeier ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 0),
  (3, 2, 'flex_product', 13765, 'Tokio Marine', 1, NULL, '["Tokio Marine ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 1),
  (4, 2, 'flex_product', 13817, 'Department of Premier and Cabinet Office of Early Childhood', 1, NULL, '["Department of Premier and Cabinet Office of Early Childhood ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 2),
  (5, 2, 'flex_product', 13830, 'Liberty WS2 Pty Ltd', 1, NULL, '["Liberty WS2 Pty Ltd ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 3),
  (6, 2, 'flex_product', 13847, 'Curae Law', 1, NULL, '["Curae Law ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 4),
  (7, 2, 'flex_product', 13880, 'Pilbara Ports', 1, NULL, '["Pilbara Ports ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 5),
  (8, 2, 'flex_product', 13883, 'The Perth Mint', 1, NULL, '["The Perth Mint ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 6),
  (9, 2, 'flex_product', 13894, 'BHP', 1, NULL, '["BHP ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 7),
  (10, 2, 'flex_product', 13895, 'Synergy', 1, NULL, '["Synergy ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 8),
  (11, 2, 'flex_product', 13897, 'Synergy', 1, NULL, '["Synergy ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 9),
  (12, 2, 'flex_product', 13914, 'WesCEF', 1, NULL, '["WesCEF ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 10),
  (13, 2, 'flex_product', 13925, 'People2People', 1, NULL, '["People2People ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 11),
  (14, 2, 'flex_product', 13926, 'SW Accountants', 1, NULL, '["SW Accountants ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 12),
  (15, 2, 'flex_product', 13936, 'Mosman Park Bowling Club', 1, NULL, '["Mosman Park Bowling Club ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 13),
  (16, 2, 'flex_product', 13937, 'Fremantle Hospital Ladies Auxiliary', 1, NULL, '["Fremantle Hospital Ladies Auxiliary ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 14),
  (17, 2, 'flex_product', 13941, 'Crumbs In the Park - Subiaco', 1, NULL, '["Crumbs In the Park - Subiaco ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 15),
  (18, 2, 'flex_product', 13943, 'Papercup South Freo', 1, NULL, '["Papercup South Freo ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 16),
  (19, 2, 'flex_product', 13944, 'Enterprise and Business', 1, NULL, '["Enterprise and Business ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 17),
  (20, 2, 'flex_product', 13945, 'Nourish Me Wholefoods', 1, NULL, '["Nourish Me Wholefoods ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 18),
  (21, 2, 'flex_product', 13946, 'BounceInc Joondalup', 1, NULL, '["BounceInc Joondalup ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 19),
  (22, 2, 'flex_product', 13947, 'Crumbs in the wall - Osborne Park', 1, NULL, '["Crumbs in the wall - Osborne Park ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 20),
  (23, 2, 'flex_product', 13948, 'The Brand Agency', 1, NULL, '["The Brand Agency ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 21),
  (24, 2, 'flex_product', 13950, 'Alcoa', 1, NULL, '["Alcoa ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 22),
  (25, 2, 'flex_product', 13951, 'Aigle Royal Group Pty Ltd', 1, NULL, '["Aigle Royal Group Pty Ltd ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 23),
  (26, 2, 'flex_product', 13953, 'Bunnings Group Ltd (WA Support Office Ca..', 1, NULL, '["Bunnings Group Ltd (WA Support Office Ca.. ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 24),
  (27, 2, 'flex_product', 13954, 'The Deli by Greenhorns', 1, NULL, '["The Deli by Greenhorns ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 25),
  (28, 2, 'flex_product', 13956, 'Bennett Litigation and Commercial Law', 1, NULL, '["Bennett Litigation and Commercial Law ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 26),
  (29, 2, 'flex_product', 13957, 'Kafič', 1, NULL, '["Kafič ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 27),
  (30, 2, 'flex_product', 13958, 'North West Shelf Gas Pty Ltd', 1, NULL, '["North West Shelf Gas Pty Ltd ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 28),
  (31, 2, 'flex_product', 13959, 'Hub Australia', 1, NULL, '["Hub Australia ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 29),
  (32, 2, 'flex_product', 13960, 'Jax Coffee', 1, NULL, '["Jax Coffee ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 30),
  (33, 2, 'flex_product', 13961, 'Whipper Snapper Distillery', 1, NULL, '["Whipper Snapper Distillery ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 31),
  (34, 2, 'flex_product', 13963, 'The Apron Cafe', 1, NULL, '["The Apron Cafe ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 32),
  (35, 3, 'sub_recipe', 7, 'Aioli', 2.3000000000000003, NULL, '["Mushroom, Spinach & Egg Wrap ×8","Bacon, Egg & Hashbrown Wrap ×3","Bacon, Egg & Hashbrown Wrap ×1","Bacon, Egg & Hashbrown Wrap ×12","Mushroom, Spinach & Egg Wrap ×10","Mushroom, Spinach & Egg Wrap ×1","Bacon, Egg & Hashbrown Wrap ×10","Mushroom, Spinach & Egg Wrap ×4","Bacon, Egg & Hashbrown Wrap ×1","Mushroom, Spinach & Egg Wrap ×4","Bacon, Egg & Hashbrown Wrap ×3","Bacon, Egg & Hashbrown Wrap ×10","Bacon, Egg & Hashbrown Wrap ×14","Mushroom, Spinach & Egg Wrap ×10","Bacon, Egg & Hashbrown Wrap ×6","Bacon, Egg & Hashbrown Wrap ×12"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 0),
  (36, 3, 'sub_recipe', 12, 'Mixed Berry Compote', 420, NULL, '["Muesli Yoghurt Pot ×5","Muesli Yoghurt Pot ×10","Chia Pudding Pot ×1","Muesli Yoghurt Pot ×1","Muesli Yoghurt Pot ×6"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 1),
  (37, 3, 'sub_recipe', 52, 'Chicken Caesar Salad', 10.85, NULL, '["Chicken Caesar Salad ×1","Chicken Caesar Salad ×2","Chicken Caesar Salad ×5","Chicken Caesar Salad ×4","Chicken Caesar Salad ×6","Chicken Caesar Salad ×4","Chicken Caesar Salad ×2"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 2),
  (38, 3, 'sub_recipe', 51, 'Chipotle Chicken Cous Cous Salad', 7.2, NULL, '["Chipotle Chicken Cous Cous Salad ×2","Chipotle Chicken Cous Cous Salad ×6","Chipotle Chicken Cous Cous Salad ×3","Chipotle Chicken Cous Cous Salad ×5","Chipotle Chicken Cous Cous Salad ×2"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 3),
  (39, 3, 'sub_recipe', 55, 'Mexican Beef Rice Salad', 5.6, NULL, '["Mexican Beef Rice Salad ×3","Mexican Beef Rice Salad ×2","Mexican Beef Rice Salad ×4","Mexican Beef Rice Salad ×2","Mexican Beef Rice Salad ×3"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 4),
  (40, 3, 'sub_recipe', 48, 'Pumpkin, Beetroot & Feta Salad', 2.73, NULL, '["Pumpkin, Beetroot & Feta ×1","Pumpkin, Beetroot & Feta ×3","Pumpkin, Beetroot & Feta ×2"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 5),
  (41, 3, 'sub_recipe', 13, 'Chia Pudding Mix', 0.17, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 6),
  (42, 3, 'recipe', 20, 'Mushroom, Spinach & Egg Wrap', 41, NULL, '["Mushroom, Spinach & Egg Wrap ×8","Mushroom, Spinach & Egg Wrap ×10","Mushroom, Spinach & Egg Wrap ×1","Mushroom, Spinach & Egg Wrap ×4","Mushroom, Spinach & Egg Wrap ×4","Mushroom, Spinach & Egg Wrap ×10"]', NULL, NULL, 61.5, NULL, NULL, NULL, 'pending', NULL, 7),
  (43, 3, 'recipe', 19, 'Bacon, Egg & Hash Brown Wrap', 74, NULL, '["Bacon, Egg & Hashbrown Wrap ×3","Bacon, Egg & Hashbrown Wrap ×1","Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×10","Bacon, Egg & Hashbrown Wrap ×1","Bacon, Egg & Hashbrown Wrap ×3","Bacon, Egg & Hashbrown Wrap ×10","Bacon, Egg & Hashbrown Wrap ×14","Bacon, Egg & Hashbrown Wrap ×6","Bacon, Egg & Hashbrown Wrap ×12"]', NULL, NULL, 111, NULL, NULL, NULL, 'pending', NULL, 8),
  (44, 3, 'recipe', 31, 'Muesli Yoghurt Pot', 27, NULL, '["Muesli Yoghurt Pot ×5","Muesli Yoghurt Pot ×10","Muesli Yoghurt Pot ×1","Muesli Yoghurt Pot ×6"]', NULL, NULL, 27, NULL, NULL, NULL, 'pending', NULL, 9),
  (45, 3, 'recipe', 32, 'Chia Pudding Pot', 1, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 2, NULL, NULL, NULL, 'pending', NULL, 10),
  (46, 4, 'sub_recipe', 12, 'Mixed Berry Compote', 90, NULL, '["Muesli Yoghurt Pot ×6"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 0),
  (47, 4, 'sub_recipe', 7, 'Aioli', 1.3000000000000003, NULL, '["Bacon, Egg & Hashbrown Wrap ×10","Bacon, Egg & Hashbrown Wrap ×3","Bacon, Egg & Hashbrown Wrap ×14","Mushroom, Spinach & Egg Wrap ×10","Bacon, Egg & Hashbrown Wrap ×1","Mushroom, Spinach & Egg Wrap ×4","Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×6"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 1),
  (48, 4, 'sub_recipe', 51, 'Chipotle Chicken Cous Cous Salad', 4, NULL, '["Chipotle Chicken Cous Cous Salad ×3","Chipotle Chicken Cous Cous Salad ×2","Chipotle Chicken Cous Cous Salad ×5"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 2),
  (49, 4, 'sub_recipe', 55, 'Mexican Beef Rice Salad', 2.4499999999999997, NULL, '["Mexican Beef Rice Salad ×2","Mexican Beef Rice Salad ×3"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 3),
  (50, 4, 'sub_recipe', 52, 'Chicken Caesar Salad', 4.199999999999999, NULL, '["Chicken Caesar Salad ×2","Chicken Caesar Salad ×6","Chicken Caesar Salad ×4"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 4),
  (51, 4, 'sub_recipe', 48, 'Pumpkin, Beetroot & Feta Salad', 1.95, NULL, '["Pumpkin, Beetroot & Feta ×2","Pumpkin, Beetroot & Feta ×3"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 5),
  (52, 4, 'recipe', 31, 'Muesli Yoghurt Pot', 6, NULL, '["Muesli Yoghurt Pot ×6"]', NULL, NULL, 6, NULL, NULL, NULL, 'pending', NULL, 6),
  (53, 4, 'recipe', 19, 'Bacon, Egg & Hash Brown Wrap', 47, NULL, '["Bacon, Egg & Hashbrown Wrap ×10","Bacon, Egg & Hashbrown Wrap ×3","Bacon, Egg & Hashbrown Wrap ×14","Bacon, Egg & Hashbrown Wrap ×1","Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×6"]', NULL, NULL, 70.5, NULL, NULL, NULL, 'pending', NULL, 7),
  (54, 4, 'recipe', 20, 'Mushroom, Spinach & Egg Wrap', 18, NULL, '["Mushroom, Spinach & Egg Wrap ×10","Mushroom, Spinach & Egg Wrap ×4"]', NULL, NULL, 27, NULL, NULL, NULL, 'pending', NULL, 8),
  (55, 6, 'sub_recipe', 7, 'Aioli', 0.8200000000000001, NULL, '["Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×2","Bacon, Egg & Hashbrown Wrap ×5","Mushroom, Spinach & Egg Wrap ×2","Bacon, Egg & Hashbrown Wrap ×20"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 0),
  (56, 6, 'sub_recipe', 52, 'Chicken Caesar Salad', 1.75, NULL, '["Chicken Caesar Salad ×2","Chicken Caesar Salad ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 1),
  (57, 6, 'sub_recipe', 55, 'Mexican Beef Rice Salad', 1.4, NULL, '["Mexican Beef Rice Salad ×2"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 2),
  (58, 6, 'sub_recipe', 12, 'Mixed Berry Compote', 15, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 3),
  (59, 6, 'sub_recipe', 13, 'Chia Pudding Mix', 0.17, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 4),
  (60, 6, 'sub_recipe', 51, 'Chipotle Chicken Cous Cous Salad', 0.4, NULL, '["Chipotle Chicken Cous Cous Salad ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 5),
  (61, 6, 'sub_recipe', 48, 'Pumpkin, Beetroot & Feta Salad', 0.39, NULL, '["Pumpkin, Beetroot & Feta ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 6),
  (62, 6, 'recipe', 19, 'Bacon, Egg & Hash Brown Wrap', 39, NULL, '["Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×2","Bacon, Egg & Hashbrown Wrap ×5","Bacon, Egg & Hashbrown Wrap ×20"]', NULL, NULL, 58.5, NULL, NULL, NULL, 'pending', NULL, 7),
  (63, 6, 'recipe', 32, 'Chia Pudding Pot', 1, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 2, NULL, NULL, NULL, 'pending', NULL, 8),
  (64, 6, 'recipe', 20, 'Mushroom, Spinach & Egg Wrap', 2, NULL, '["Mushroom, Spinach & Egg Wrap ×2"]', NULL, NULL, 3, NULL, NULL, NULL, 'pending', NULL, 9),
  (65, 7, 'sub_recipe', 7, 'Aioli', 0.8200000000000001, NULL, '["Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×2","Bacon, Egg & Hashbrown Wrap ×5","Mushroom, Spinach & Egg Wrap ×2","Bacon, Egg & Hashbrown Wrap ×20"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 0),
  (66, 7, 'sub_recipe', 52, 'Chicken Caesar Salad', 1.75, NULL, '["Chicken Caesar Salad ×2","Chicken Caesar Salad ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 1),
  (67, 7, 'sub_recipe', 55, 'Mexican Beef Rice Salad', 1.4, NULL, '["Mexican Beef Rice Salad ×2"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 2),
  (68, 7, 'sub_recipe', 12, 'Mixed Berry Compote', 15, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 3),
  (69, 7, 'sub_recipe', 13, 'Chia Pudding Mix', 0.17, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 4),
  (70, 7, 'sub_recipe', 51, 'Chipotle Chicken Cous Cous Salad', 0.4, NULL, '["Chipotle Chicken Cous Cous Salad ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 5),
  (71, 7, 'sub_recipe', 48, 'Pumpkin, Beetroot & Feta Salad', 0.39, NULL, '["Pumpkin, Beetroot & Feta ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 6),
  (72, 7, 'recipe', 19, 'Bacon, Egg & Hash Brown Wrap', 39, NULL, '["Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×2","Bacon, Egg & Hashbrown Wrap ×5","Bacon, Egg & Hashbrown Wrap ×20"]', NULL, NULL, 58.5, NULL, NULL, NULL, 'pending', NULL, 7),
  (73, 7, 'recipe', 32, 'Chia Pudding Pot', 1, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 2, NULL, NULL, NULL, 'pending', NULL, 8),
  (74, 7, 'recipe', 20, 'Mushroom, Spinach & Egg Wrap', 2, NULL, '["Mushroom, Spinach & Egg Wrap ×2"]', NULL, NULL, 3, NULL, NULL, NULL, 'pending', NULL, 9),
  (75, 8, 'sub_recipe', 7, 'Aioli', 2.16, NULL, '["Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×2","Bacon, Egg & Hashbrown Wrap ×5","Mushroom, Spinach & Egg Wrap ×2","Bacon, Egg & Hashbrown Wrap ×20","Bacon, Egg & Hashbrown Wrap ×20","Bacon, Egg & Hashbrown Wrap ×4","Mushroom, Spinach & Egg Wrap ×4","Bacon, Egg & Hashbrown Wrap ×25","Bacon, Egg & Hashbrown Wrap ×10","Mushroom, Spinach & Egg Wrap ×4"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 0),
  (76, 8, 'sub_recipe', 52, 'Chicken Caesar Salad', 1.75, NULL, '["Chicken Caesar Salad ×2","Chicken Caesar Salad ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 1),
  (77, 8, 'sub_recipe', 55, 'Mexican Beef Rice Salad', 1.75, NULL, '["Mexican Beef Rice Salad ×2","Mexican Beef Rice Salad ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 2),
  (78, 8, 'sub_recipe', 12, 'Mixed Berry Compote', 15, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 3),
  (79, 8, 'sub_recipe', 13, 'Chia Pudding Mix', 0.17, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 4),
  (80, 8, 'sub_recipe', 51, 'Chipotle Chicken Cous Cous Salad', 0.4, NULL, '["Chipotle Chicken Cous Cous Salad ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 5),
  (81, 8, 'sub_recipe', 48, 'Pumpkin, Beetroot & Feta Salad', 0.78, NULL, '["Pumpkin, Beetroot & Feta ×1","Pumpkin, Beetroot & Feta ×1"]', NULL, NULL, 0, NULL, NULL, NULL, 'pending', NULL, 6),
  (82, 8, 'recipe', 19, 'Bacon, Egg & Hash Brown Wrap', 98, NULL, '["Bacon, Egg & Hashbrown Wrap ×12","Bacon, Egg & Hashbrown Wrap ×2","Bacon, Egg & Hashbrown Wrap ×5","Bacon, Egg & Hashbrown Wrap ×20","Bacon, Egg & Hashbrown Wrap ×20","Bacon, Egg & Hashbrown Wrap ×4","Bacon, Egg & Hashbrown Wrap ×25","Bacon, Egg & Hashbrown Wrap ×10"]', NULL, NULL, 147, NULL, NULL, NULL, 'pending', NULL, 7),
  (83, 8, 'recipe', 32, 'Chia Pudding Pot', 1, NULL, '["Chia Pudding Pot ×1"]', NULL, NULL, 2, NULL, NULL, NULL, 'pending', NULL, 8),
  (84, 8, 'recipe', 20, 'Mushroom, Spinach & Egg Wrap', 10, NULL, '["Mushroom, Spinach & Egg Wrap ×2","Mushroom, Spinach & Egg Wrap ×4","Mushroom, Spinach & Egg Wrap ×4"]', NULL, NULL, 15, NULL, NULL, NULL, 'pending', NULL, 9)
ON CONFLICT DO NOTHING;