[phases.setup]
nixPkgs = ["nodejs_20", "tesseract", "ffmpeg", "poppler_utils", "imagemagick", "python3", "python3Packages.pdfplumber", "python3Packages.pillow", "python3Packages.img2pdf"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node dist/index.cjs"
